# Generated by Django 2.1.4 on 2018-12-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=255, unique=True)),
                ('cidr', models.CharField(max_length=255)),
                ('net_mask', models.CharField(max_length=255, null=True)),
                ('location', models.IntegerField(choices=[(1, 'New York'), (2, 'Tampa'), (3, 'Portland')])),
                ('environment', models.IntegerField(choices=[(1, 'development'), (2, 'test'), (3, 'production')])),
            ],
        ),
    ]
